### ISSUE TITLE
Issue #02 - MVP List

### ISSUE THREAD

**Issue by keginzburg** [wcorona269/myTable#2]
# MVP List
- [X] Should have 7 MVPs.
  - [X] 3 of those are User Auth, Heroku, and Production README.
  - [X] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [X] Contains a description sentence of the app
- [X] Includes two to three detailed bullets on functionality and presentation of feature
- [ ] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [X] Estimates how long it will take the code each MVP
- [X] Correctly formatted
  - [X] MVPs are listed in an ordered list
  - [X] Each MVP is broken down into bullet points

## Comments
Please add CRUD specifications to all of your MVPs.
I would start with seeding Restaurant Data and Reservations MVP before attempting Search.

1. Heroku Hosting
    1. Should only take 1/2 day. Leaving you 1 full day to allocate to your schedule.
2. User Auth
    1. I would add Splash Page to this MVP as it is mostly styling and all functionality in it will point to User Auth.
    2. Also add error handling when it comes to user errors when attempting to sign up and sign in.
    3. I’d specify what users can do without logging in for this MVP.
    4. Demo/Guest Login is expected in this MVP and not considered a Bonus. 
3. Restaurant Search
    1. You’ve nixed the Create Restaurants, which is okay, but I think you need to elaborate more on this section.
    2. What can Users see when it comes to Searching Restaurants and how can they interact in this MVP?
4. Restaurant Views & Reservations
    1. This is a big MVP as well, so I’d like some more elaboration on what users will see here and how they can interact with this MVP.
5. Reviews
    1. Will a user be able to leave a review for future reservations or only past reservations?
    2. How much CRUD is involved in this MVP?
6. Bonuses
    1. I would add more Profile functionality as a Bonus.

**Comment by wcorona269** [comment]
Hi Kyle, I've reworked my MVP list according to your suggestions. Thank you!
