### ISSUE TITLE
Issue #03 - Schema

### ISSUE THREAD

**Issue by keginzburg** [wcorona269/myTable#3]
# Database Schema
- [X] Contains correct datatypes
- [X] Contains appropriate constraints/details
  - [X] primary key
  - [X] not null
  - [X] unique
  - [X] indexed
  - [X] foreign key
- [X] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [X] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
  - [x] schema is written in a table format
  - [X] the table’s name are lowercased, snake_cased and `back_ticked`
  - [X] the table header column names are bolded
  - [X] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
1. Users
    1. Will Users add their first and last name when creating an account? Is this needed in your database? Is any other information needed as well?
2. Restaurants
    1. Not a huge issue, but do we want restaurant names to be unique on your backend (maybe to stop someone from adding multiple entries for the same restaurant)?
    2. Will you need to do data type conversion for your price range when retrieving that data?
    3. Description of restaurants? Or does that fall under cuisine?
    4. Will restaurants have photos? Is that a separate table necessitating joins?
    5. Just a suggestion, could we utilize an association here based on how many times a restaurant has been saved by users to dictate which restaurants are more popular?
3. Reviews
    1. Markdown formatting issues here with your table.
    2. Lots of ratings here. Are you planning on averaging out your detailed ratings for your overall rating or giving the user-controlled input for the overall?
    3. Also, will users only be able to leave one review for each restaurant or for each experience? If the former, should we use indexing here?
4. Reservations
    1. Should we index our foreign keys here?
5. Saved_Restaurants
    1. Timestamps?

**Comment by wcorona269** [comment]
Hi Kyle,

I've added most of these recommendations to my table. I have a few replies to your comments:

- Price range will be an integer between 1 and 4 represented by dollar signs. So $ = cheapest, $$$$ = most expensive.
- the overall rating will be it's own rating, no need to average out other ratings. Ratings will be visually represented within the 5-star metric, and restaurant rating will be an average of overall ratings from all reviews.

**Comment by keginzburg** [comment]
Sounds good. Looking forward to what you have today.
